# Generated by Django 4.2.3 on 2023-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gesture',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('subtitle', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILURE', 'Failure')], default='QUEUED', max_length=10)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
