# Generated by Django 4.2.3 on 2023-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesture',
            name='characters_not_found',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gesture',
            name='duration',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='gesture',
            name='generated_duration',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='gesture',
            name='words',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gesture',
            name='words_not_found',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
